# Imports & Set Up

In [1]:
import pandas as pd
import scipy.stats as stats
from statsmodels.formula.api import ols
import statsmodels.api as sm
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multicomp import MultiComparison

# 50 Schools

In [2]:
data_schools = pd.read_csv('50_Schools_Data.csv')
data_schools = data_schools.rename(columns={"Rating Count": "RC",'Unnamed: 0': 'CodeKeys'})

In [3]:
data_schools

    CodeKeys                                        School    Rating      RC
0          0                         University of Wyoming  3.726242    3091
1          1             University of Wisconsin - Madison  3.785536   47657
2          2                      West Virginia University  3.805346   23026
3          3                      University of Washington  3.784432   41845
4          4                       George Mason University  3.777748   74811
5          5                         University of Vermont  3.707608   17457
6          6                      Brigham Young University  4.026193   85179
7          7       Texas A&M University at College Station  3.718053   31903
8          8           University of Tennessee - Knoxville  3.758922   38817
9          9                 South Dakota State University  3.655382    4917
10        10                  University of South Carolina  3.803050   59665
11        11                    University of Rhode Island  3.698183   24351
12        12                 Pennsylvania State University  3.692498   65250
13        13                     Portland State University  3.684162   32920
14        14                        University of Oklahoma  3.751911   19796
15        15                     The Ohio State University  3.792001   65355
16        16                    University of North Dakota  3.644255    9539
17        17               North Carolina State University  3.706634   21797
18        18          University at Buffalo (SUNY Buffalo)  3.716457   34161
19        19                         University of Alabama  3.883831   46667
20        20                University of Alaska Anchorage  3.815543   16029
21        21                      Arizona State University  3.683456  113095
22        22                        University of Arkansas  3.762967   33118
23        23   University of California Los Angeles (UCLA)  3.759124    4437
24        24              University of Colorado - Boulder  3.659779   17901
25        25                     University of Connecticut  3.648709   25491
26        26                        University of Delaware  3.697481   55942
27        27                 University of Central Florida  3.755060  105495
28        28                         University of Georgia  3.856353   43832
29        29                 University of Hawaii at Manoa  3.850891   26518
30        30                        Boise State University  3.748868   23045
31        31  University Of Illinois at Urbana - Champaign  3.669187   31040
32        32                Indiana University Bloomington  3.727530   32709
33        33                            University of Iowa  3.693351   21306
34        34                          University of Kansas  3.739869   25562
35        35                        University of Kentucky  3.770909   26467
36        36                    Louisiana State University  3.687452   23579
37        37                           University of Maine  3.709472   14752
38        38                        University of Maryland  3.662491   18985
39        39                   University of Massachusetts  3.677342   41703
40        40                     Michigan State University  3.633107    9592
41        41           University of Minnesota-Twin Cities  3.698954   49263
42        42                  Mississippi State University  3.571484    5902
43        43             University of Missouri - Columbia  3.666450   17694
44        44                      Montana State University  3.696954    4612
45        45                University of Nebraska-Lincoln  3.633749   16066
46        46                University of Nevada Las Vegas  3.866901   51608
47        47    University of New Hampshire (all campuses)  3.692107   14968
48        48      Rutgers - State University of New Jersey  3.766381   71220
49        49                      University of New Mexico  3.769516   28481

In [4]:
# we are looking at Rating

In [5]:
anova_rating = ols('Rating~CodeKeys', data=data_schools).fit()
anova_rating.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Rating   R-squared:                       0.083
Model:                            OLS   Adj. R-squared:                  0.064
Method:                 Least Squares   F-statistic:                     4.337
Date:                Tue, 31 Dec 2019   Prob (F-statistic):             0.0427
Time:                        11:10:06   Log-Likelihood:                 59.207
No. Observations:                  50   AIC:                            -114.4
Df Residuals:                      48   BIC:                            -110.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.7716      0.021    179.103      0.000       3.729       3.814
CodeKeys      -0.0015      0.001     -2.082      0.043      -0.003   -5.32e-05
==============================================================================
Omnibus:                       15.475   Durbin-Watson:                   1.922
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               18.662
Skew:                           1.143   Prob(JB):                     8.86e-05
Kurtosis:                       4.931   Cond. No.                         56.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
anova_table = sm.stats.anova_lm(anova_rating)
print(anova_table)

            df    sum_sq   mean_sq         F    PR(>F)
CodeKeys   1.0  0.024767  0.024767  4.336672  0.042653
Residual  48.0  0.274132  0.005711       NaN       NaN

In [7]:
mc = MultiComparison(data_schools['CodeKeys'], data_schools['Rating'])
mc_results = mc.tukeyhsd()
print(mc_results)

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3506: RuntimeWarning: Degrees of freedom <= 0 for slice
  **kwargs)
/opt/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

ValueError: v must be > 1 when p >= .9

In [ ]:
data_schools['Rating'].corr(data_schools['RC'])

# Departments (PSU)

In [12]:
data_department = pd.read_csv('Department_Data.csv')

FileNotFoundError: [Errno 2] File b'Department_Data.csv' does not exist: b'Department_Data.csv'

In [ ]:
data_department.drop(columns='Unnamed: 0')

In [ ]:
data_department=data_department.rename(columns={'Unnamed: 0': 'CodeKeys'})

In [8]:
data_department

NameError: name 'data_department' is not defined

In [9]:
anova_rating = ols('Rating~CodeKeys', data=data_department).fit()
anova_rating.summary()

NameError: name 'data_department' is not defined

In [10]:
anova_table = sm.stats.anova_lm(anova_rating)
print(anova_table)

            df    sum_sq   mean_sq         F    PR(>F)
CodeKeys   1.0  0.024767  0.024767  4.336672  0.042653
Residual  48.0  0.274132  0.005711       NaN       NaN

In [11]:
mc = MultiComparison(data_department['CodeKeys'], data_department['Rating'])
mc_results = mc.tukeyhsd()
print(mc_results.summary())

NameError: name 'data_department' is not defined

In [ ]:
https://www.ratemyprofessors.com/filter/professor/?&page=1&filter=teacherlastname_sort_s+asc&query=*%3A*&queryoption=TEACHER&queryBy=schoolId&sid=758